@cookies-admin = next-auth.session-token=6ac82a67-5805-4c53-8d5b-20a50d43186a
@cookies-default = next-auth.session-token=7ce88ec3-7158-4d48-a7c7-75fcd4f107b8
###
GET http://localhost:3000/cards?name=MASKED%20HERO%20DARK

###
http://192.168.0.95:3000/cards?name=MASKED%20HERO%20DARK


###
GET http://localhost:3000/users



###
POST http://localhost:3000/purchase
Content-Type: application/json
Cookie: {{cookies-admin}} 

{
  "name": "Purchase 1",
  "startDate": "10/05/2025",
  "endDate": "10/31/2025"
}


###
GET http://localhost:3000/purchase
Cookie: next-auth.session-token=6ac82a67-5805-4c53-8d5b-20a50d43186a



###

GET http://localhost:3000/purchase?onylActive=true

###
POST http://localhost:3000/shopping-list
Content-Type: application/json
Cookie: next-auth.session-token=6ac82a67-5805-4c53-8d5b-20a50d43186a

{
  "purchaseId": "ebfabff8-d878-4b14-a89e-96b5edd55cc0",
  "items": [
    {
      "cardId": 10920352,
      "rarityId": "83711c50-8b79-4917-ba34-89de76e21a95",
      "collection": "Collection C",
      "quantity": 3,
      "unit_price":30
    },
    {
      "cardId": 58147549,
      "rarityId": "29add11e-a97c-4a68-b72b-68c3c15b22a6",
      "collection": "Collection C",
      "quantity": 3,
      "unit_price":30
    }
  ]
}


###
GET http://localhost:3000/shopping-list/user/d4a956dd-88c8-42d0-a011-66114f3ff651
Cookie: {{cookies-admin}}


###
GET http://localhost:3000/shopping-list/user/80282180-e3fe-4aa1-ad02-c023ad35eee7
Cookie: {{cookies-admin}}


###
GET http://localhost:3000/shopping-list/user/80282180-e3fe-4aa1-ad02-c023ad35eee7
Cookie: {{cookies-admin}}


###
GET http://localhost:3000/shopping-list/336a39d4-212e-4a0e-a18f-56810f98021b
Cookie: {{cookies-admin}}

###

GET http://localhost:3000/shopping-list/purchase/ebfabff8-d878-4b14-a89e-96b5edd55cc0
Cookie: {{cookies-admin}}



###

GET http://localhost:3000/shopping-list/purchase/71f012f7-6a34-412e-8096-c898d1d47a1f/final
Cookie: {{cookies-admin}}


###
GET http://192.168.0.95:3000/rarities

###
GET http://192.168.0.95:3000/cards


###
GET http://localhost:3000/users/admin
Cookie: {{cookies-admin}}


###
GET http://localhost:3000/shopping-list/purchase/71f012f7-6a34-412e-8096-c898d1d47a1f/export-excel
Cookie: {{cookies-admin}}