services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ygo
      POSTGRES_USER: ygo
      POSTGRES_PASSWORD: ygo
    volumes:
      - yu_gi_oh_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ygo"]
      interval: 5s
      timeout: 5s
      retries: 3
  app:
    build: . 
    container_name: my_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  yu_gi_oh_db: